# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-21 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='unfavourite',
            field=models.BooleanField(default=True),
        ),
    ]
